language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "Hz6f6WEnzspw/1llUXY2aFWIHDkJkvWpM7q8ysl10G+eAmVytHb4wIBcEoAxIFb8+4L87w6bSGr9KXCD36POgKSfM0BgRGieiHw7Yu1jNY7BXdVjP7SnVrkZwGJ6WNvcrqlZBVyCt2BmRASv+sqmJ8I9InBS84zdgvbQtfPZ6JRGmuqQwsoz5n1sL0tFKuL4JNAh+Q82kjZx8cA0cbtQgYUBdsTCWAVnNNm9GawrEkccOhiTcXlYwa1oZcJX6Mj7DzIVZFEN9r56Ziyd9eilyMRmLsfH126Tqlom7u35GD0gKtWc5yZqQIz0shnelGdNfQF7xcDGSpD/Vjj7uh+Nv0Lfe3pJX0eAJHGGX4r6wdx2fJxypFOXmSWaVKglTSGSclIeT8H+nVSIrOu+fVGePtkZd4eALpznPHhKxNVZqkDdsHpi6+Q0sIBjwOXLbY1kOlwU7obl+kirk4Zb0gGi4vHPmdnvozA/wEP/J0ZD10q+c/P39AhHmaN7rMjvpN8om8UhxMDvncm4A+LNa/ySMxqegrT4nY+/Og39nDSA5XmfM1dGZnBtSAd6HfabITf4ajpn1HTh6Hm0CO9GxYkdEprA/Gxiy/UBgwPUeNwHzXckrkE+z1ifj66uTs1Crx8cWR6JsWlEeTWli67qY+vTdy/xPUIGSZXB15+myfAI1kI="
  - secure: "bkxc6uPSkqJQAR1QOGSeQEXQzN0deUEL3rgYCvMiuO+elUIWckXip96468AB9pycmW+AeazcDT9LJfzxiVqxYPNeZbJvsTjBSQBRNsrJwWMwRFWux8Yab5PJMJhNaje7dDLRYlSYc2Dx9N3GBwe45glMRYIhQQs87mFYH9Fg4tiYACwxLQu/Q27IE22tQebWmMJEvUjuGwnXnue0lLaTuueruu2T6qFQ8ZU4uNBBfC31WFx6Gxw8PrWsPoWtmZ2jmdYDiECJchzxC/vewXSYjov4sGiu7dsRF38V4nNwKTZXcksva5HvBWDs79WLdCDWCAxt+GLA18v5894tfEnni4PMlo8QcmPLvk+HLZMalm9FCMQWlj2kAAff3+qo5JwQFvhmYf0GscsV1wQuC9seOLZf0nSW8nYDCzOk/HJKV0sGDOIjAXJxKkxEC6y1z0mDM3G2nQZWRNDV7JVtwENE5SlbecRMj/jbkIMaRqz3bnpitci9lKACDxwKIvahL1QEQuwEnniosbti1HRCTIAuG1SNPh8vA9N1YH5ptlIR3KuWXuBbN53jdlYMVYfrtuiPe0jDlenGXJrvKngvlMb9wfYr8zNldLhSr8lcFv/+tw+72E8vKtBhxiovd4lSzMRXjp0Za9TTOl+R1xwqoGNMbDGp2jT6Q7lOfrIyvX5csPM="
  - secure: "D6DystDIIrLg+4ZE1tz7H0EMJi7lRWXK4DdGM49O0Mt++690KzEqbIMgs+ZjZDxX5qJO/v+Kxuo2CTvyyFVVdqP9NZVPDnIH57wttIRuxKeNSAvi8Bn9sHu4UpLW5equSDqsmYoat9rkUtjT9EvwzR2hEYgEJ+y9bOYqUgHmtaEj47kLsX7temKUmwk7tzXUEZnpqv615HwNWVWVuPlzkzBz4V+ZkFuiRZalcjWJce1kUxeLBwgA3IYb3P2RdCgtkrhydgsKwqZ9jg4B95bzWo2jfqbnmaiGLboE1hyLPpcWmchKDhAiM5TWGs6iLvPR+jpvD2TdUtXjF64LCUiFqRN2X9QfJB+SswKetVqeTLhb0QapsHp/PBW7W/TdOBFsr8fqYZQ4a6InEbv4KVPejj9Lt7Jf2wDIdlRNGBD6HlByOiB5t8LjvdFpo9Su3xCuVcr8jsOBX9FLj4lwICnNFbSK5wRYA2HlBLV2J6yY+JpJRPF/g9S4HhV2lZcVPrmR8tphySHqIMUHWC/u8FpLu2GGiJiw1LEeQGInt1rn3ny1349HZurcZH72V8YeVBu9xtEyHrLrkYFw+1ruJCX3k7FYAR+kWOA0D/d20qXkOkxrp3/l2Q5lN91WC/3DmZlcpztE7wIecL3Lb9+cUTVUNRlGUckd8QOOt1NWFs6yGzM="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_1963fd6ce20c_key -iv $encrypted_1963fd6ce20c_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi