language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: Y7J6T97CJTN/A9SXoi73mFKBRCW17qRBWYKSo5uemXFVd5VAQLmHuJwIG4WHEylttN4u2boXeSZ0cfEj+H/whyFqfp52I+Tt/pjvWV4M/frG0ScD9WYNJDCajJ5D0uhGeDIdkwAMyvA6scDcXd8bZZ918ppfga5Wf5W5HfnuzTYGc+H6Ad8BtC5YXZ83JYL1pDe9fOezA3aOYqQjlAUD5FQhYDL908Dgqqo07ui46OCv/+1RRHwAYuEaFfwbbAzZKW2El4bLMK9ZCtDWYlEJRuGBLoXn2PI8urTroe3TY4DF4Sry6Lo6hYLuhW6jY0QdAsBo7jPmG6y66UoOk21HJk2KWhYla3w8IY/gf3VhzC+1/Oq0FoGCzCB1zmsopAtoVCERMRuE7c8byW5+4j5rjD1xDmGZqmYYTpNuDvhPJzeTFwpQLvKoNbev0Tvqr+1oQj+KpbokaqJqwrujsvRNqVtko3eHHJkvP9kJrEv+2FKDISBXSTdn01yJkDhp7FWM7lVtCU1H1eEZOSlo8UcJzyQhP3UldLoCWYFP7Re1r2OLAvtH3QH93gzKrolufL6mFRhqUmlGa9aYWZK0xhX90EdJ7LOMU54qGJiEnMAkf3bwa0pJIX7AiDpEXZRAXTX+oaOdWECU1ErUtG7B/XLfJvfVmewxgKOOqjbU03rsNK4=
  - secure: BFQXfmrQAJLEHzGEcO3bQuzyzB8NbX9UWK9aineVYN3DfOX1Z1r0mDVuXTmlJ4591mlG9Bkn+rLgXyA0p6ZHPNsuasfNacx5l9pZO6aiTUignpib91uEpOAUnH9FPW0mOw53zJsa02nH45QgAzSDWcO4qWREPLGk0Rr1hNzksKlwscl7JjemA8cDoNVBWeIGAZE4oRk8CFmCccqjzuLDzlOPP6T+dIu3cgjGAKdTTXsYzWMtgT0ZSpEd+iS2EvVmDFFVN3R4PQCCzuP1bnLzi3iPTmogQmLLwx6TQ35f0NT7I0TkTD3wg7dZfdsL9iQPAJSc4qlVHbTQXC2AVltIc7q8RfKm/y/Fij+V7QoOri0kuVXcJ2KaMHL+FRChqkSeWMBXNEFeO81kpY8vgQ3zKRHIOP9cjMG0R48xXVzL6tEO5Amc9VEWAZrbfbUVHDdZSBFaX7ThBWu0B3FJK8h0G/iEgxT1zVbcLj/b1hu0ox+gjPduyj8w/aJ4fTw4GLrD3GpLyggD0MosaJJ9xT1Ps5gTLgwGUtglqQxP1aePLkNMArCR2tQz8XrIWiydje/NWNXlrkpg46qaug386xEoEySyHyC56jPxHdm4u9RIWbC0MaS5OFUhdFcHGOLObQ84DHJ8bKd29Ypzg220gMgv5ms7IOjbKvhix3+84viRvyI=
  - secure: Deqxp6gOtW/OUkXtkbSItwo6HtrsQJ5qWvRAnJ2fsloj8xiDjM1qc0fwxHeL9AoOQin89M7hX4bOtx2h3UCfNtjJGbabYiWv70etfjHCe9jR3ZgXFlFw0DCKmqy2BEhHC3stn/TWJMoObRAYdS7Hf156zYi0XAAUNLqxu3TpmZnXH7U9xc92+StchhJOXnSt7CqfFFQJUUDCeNrvnVC+MBTSeWaC49qJk56sqIoQ+6Ou8OzXxCYsycBO+c9YMnaLI51ew8fJFV/fzpYqePcAyQ9m19M/pFErLDF1cX464b4q/eRex79vtyvI1AC8qM5+rLUBiJ9Z4F/xcPkvZYDWnTX8su/f0zZGWAC3N0L+tKs2+YJqUXkWJI8gN0h0ALIhEuLn6ZMPVFg0K9b+JsAXcSoKXomLLgwoi9/+/mrXFA1FRQN/ys+3H2xr6TgsNAj+B9EGdaYYpm+RF1FB0DOu2UAAGrA31iV+msCyXZeGkm3+I7WsY83qlS9fS/x3STiu8xrnxspJhkU6EWBgX0jAAAi+QyVC0yHP9ZMGSpc2e9K0Q3Upeo1MY4hF12mDwRsmZ2hI9vcB/Key1PSz3pTV3MvSOktdMfEwYhx2OQoWzxm++0KJ/gQ0PTo6wG52YiF/BTa436eHvlNABThiScHu5/HXJiYvnsNbGDntP7gLoEo=

before_install:
- openssl aes-256-cbc -K $encrypted_22416fdd1e1b_key -iv $encrypted_22416fdd1e1b_iv
  -in gpg.tar.gz.enc -out gpg.tar.gz -d
- tar zxvf gpg.tar.gz

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U

script: mvn test

after_success:
- mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml